In [12]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import seaborn as sns

In [65]:
data = pd.read_csv("https://raw.githubusercontent.com/Zipcoder/DataEngineering.Labs.WineQuality/\
master/Combined%20Wine%20Data.csv?token=ALOLXONPYPXMSJ6T4KTISB26BZHLG")

In [66]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

Let's jump into feature engineering. To quote Wikipedia:

    "Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work."
    
In practical terms, feature engineering is just adding to a data set, using your domain knowledge.

To show this - let's start with a very simple example. Let's go back to our earlier example. Let's add a column to our data set that simply indicates whether a wine has above average sweetness or not. In reality, this is probably not a super helpful feature, but we can take what we learn here, and then you can create your own features.

In [67]:
#for this simple example, let's use numpy

data['sweet?'] = np.where(data['residual sugar'] >= data['residual sugar'].mean(), True, False)

In [68]:
#see? now we've added a column that marks whether that particular wine is above average for sweetness
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,sweet?
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,False
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,False
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,False
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,False
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,False

Let's get a little more complex now. Let's add a column based on multiple conditions. I want to find wines that are:

 - Ranked 6 or higher in the quality column
 - Above average sweetness
 - Above the 75% percentile in alcohol content
 - Reds only

In [69]:
#let's define our qualities up front

quality = 6
sweet = True
alcohol = data.alcohol.quantile(0.75)
color = 'red'

In [82]:
#this is a little messy, but try to follow along here. reading the docs for np.logical_and() might help :)

condition = np.logical_and(data['quality'] >=quality, data['sweet?'] == sweet)
condition = np.logical_and(condition, data['alcohol'] > alcohol)
condition = np.logical_and(condition, data['color'] > color)

In [83]:
condition.value_counts()

False    6212
True      285
dtype: int64

In [85]:
data['I like it'] = condition

In [58]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,sweet?
1665,6.4,0.26,0.24,6.4,0.040,27.0,124.0,0.99030,3.22,0.49,12.60,7,white,True
1749,7.9,0.22,0.38,8.0,0.043,46.0,152.0,0.99340,3.12,0.32,11.50,7,white,True
1774,6.9,0.23,0.40,7.5,0.040,50.0,151.0,0.99270,3.11,0.27,11.40,6,white,True
1791,6.8,0.28,0.36,8.0,0.045,28.0,123.0,0.99280,3.02,0.37,11.40,6,white,True
1802,6.8,0.26,0.34,13.9,0.034,39.0,134.0,0.99490,3.33,0.53,12.00,6,white,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6436,6.5,0.28,0.38,7.8,0.031,54.0,216.0,0.99154,3.03,0.42,13.10,6,white,True
6439,6.8,0.34,0.36,8.9,0.029,44.0,128.0,0.99318,3.28,0.35,11.95,7,white,True
6456,7.5,0.38,0.33,9.2,0.043,19.0,116.0,0.99444,3.08,0.42,11.40,6,white,True
6469,6.1,0.32,0.28,6.6,0.021,29.0,132.0,0.99188,3.15,0.36,11.45,7,white,True
6485,6.2,0.21,0.28,5.7,0.028,45.0,121.0,0.99168,3.21,1.08,12.15,7,white,True

In [55]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color,sweet?
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red,False
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red,False
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red,False
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red,False
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white,False
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white,True
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white,False
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white,False
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white,False